# Generated by Django 5.2.4 on 2025-07-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('technology', models.CharField(max_length=100, verbose_name='Tecnología')),
                ('createt_At', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
        ),
    ]
